include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Suppress errors in locked files that cannot be modified
    # The non_bool_operand error in stt_engine_speech_to_text.dart is due to
    # speech_to_text API change (hasPermission became Future<bool>)
    # This is a known issue that requires locked file modification to fix
    non_bool_operand: ignore
    # Suppress deprecation warnings from locked files
    deprecated_member_use: ignore
    # Suppress unreachable switch default warnings from locked files
    unreachable_switch_default: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
